<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="15476" started-at="2018-03-12T12:30:13Z" finished-at="2018-03-12T12:30:28Z">
    <groups>
    </groups>
    <test name="loans" duration-ms="15476" started-at="2018-03-12T12:30:13Z" finished-at="2018-03-12T12:30:28Z">
      <class name="framework.Login">
        <test-method status="FAIL" signature="login()[pri:0, instance:framework.Login@15eef3d]" name="login" duration-ms="15259" started-at="2018-03-12T18:00:13Z" finished-at="2018-03-12T18:00:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Wings - Banking Application Software] but found [IRIS - Banking Application Software]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Wings - Banking Application Software] but found [IRIS - Banking Application Software]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at common.VerifyTitle.verify(VerifyTitle.java:17)
	at framework.LoadActionKeys.actionkeys(LoadActionKeys.java:189)
	at framework.DriverScript.loadExcel(DriverScript.java:57)
	at framework.Login.login(Login.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="handle()[pri:0, instance:framework.Login@15eef3d]" name="handle" is-config="true" duration-ms="188" started-at="2018-03-12T18:00:28Z" finished-at="2018-03-12T18:00:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handle -->
      </class> <!-- framework.Login -->
    </test> <!-- loans -->
  </suite> <!-- Suite1 -->
</testng-results>
